### ISSUE TITLE
ImportError: dynamic module does not define init function (initbpy)

### ISSUE THREAD

**Issue by napter** [bcongdon/bpy_lambda#8]
When trying to run "from bpy_lambda import bpy" on an amazon linux ec2 instance (the same version used by lambda) I get the following error:

```
[ec2-user@ip-172-31-12-230 aws-lambda-xvfb-master]$ python /home/ec2-user/blender.py
/usr/local/lib/python2.7/site-packages/bpy_lambda/libHalf.so.12
/usr/local/lib/python2.7/site-packages/bpy_lambda/libIex.so.12
/usr/local/lib/python2.7/site-packages/bpy_lambda/libImath.so.12
/usr/local/lib/python2.7/site-packages/bpy_lambda/libIlmThread.so.12
/usr/local/lib/python2.7/site-packages/bpy_lambda/libIlmImf.so.22
/usr/local/lib/python2.7/site-packages/bpy_lambda/libboost_system.so.1.60.0
/usr/local/lib/python2.7/site-packages/bpy_lambda/libboost_filesystem.so.1.60.0
/usr/local/lib/python2.7/site-packages/bpy_lambda/libboost_regex.so.1.60.0
/usr/local/lib/python2.7/site-packages/bpy_lambda/libboost_thread.so.1.60.0
/usr/local/lib/python2.7/site-packages/bpy_lambda/libpython3.6m.so.1.0
/usr/local/lib/python2.7/site-packages/bpy_lambda/libGLU.so.1
/usr/local/lib/python2.7/site-packages/bpy_lambda/libopenjpeg.so.2
/usr/local/lib/python2.7/site-packages/bpy_lambda/libOpenImageIO.so.1.7
Traceback (most recent call last):
  File "/home/ec2-user/blender.py", line 1, in <module>
    from bpy_lambda import bpy
  File "/usr/local/lib/python2.7/site-packages/bpy_lambda/__init__.py", line 26, in <module>
    from . import bpy
ImportError: dynamic module does not define init function (initbpy)
```

**Comment by napter** [comment]
The error only happened in Python 2.7. It worked in 3.6
